local NAME="BF Dashboard"
local VERSION="v1.4"
local BASE_W,BASE_H=480,272
local UI_SCALE=1
local function X(v)return math.floor(v*UI_SCALE+0.5)end
local function Y(v)return math.floor(v*UI_SCALE+0.5)end
local function S(v)return math.floor(v*UI_SCALE+0.5)end
local CYAN=lcd.RGB(0,200,255)
local bg,bg_loaded,default_pic,model_pic=nil,false,nil,nil
local icons,cache={},{}
local last_rtc,armed_seconds,was_armed=0,0,false
local max_current,max_power,max_speed=0,0,0
local options={{"SquareColor",COLOR,WHITE},{"BackgroundColor",COLOR,BLACK},{"UsePngBg",BOOL,1},{"ValueColor",COLOR,GREEN},{"ShowImage",BOOL,1},{"CellCount",VALUE,0,0,12}}
local function field(names)for i=1,#names do local f=getFieldInfo(names[i]);if f then return f.id end end end
local function sensor(names,def)local k=table.concat(names,"/");if cache[k]==nil then cache[k]=field(names)or false end;local id=cache[k];if id then local v=getValue(id);if v~=nil then return v end end;return def or 0 end
local function num(v,d)if type(v)=="number"then return v end;if type(v)=="string"then local n=tonumber(v);if n then return n end;local m=string.match(v,"%-?%d+%.?%d*");return tonumber(m)or d or 0 end;return d or 0 end
local function str(v,d)if v==nil then return d or"--"end;return tostring(v)end
local function box(x,y,w,h,c)lcd.drawRectangle(X(x),Y(y),S(w),S(h),c)end
local function hl(x,y,w,c)lcd.drawLine(X(x),Y(y),X(x+w),Y(y),SOLID,c)end
local function vl(x,y,h,c)lcd.drawLine(X(x),Y(y),X(x),Y(y+h),SOLID,c)end
local function loadbg()if bg_loaded then return end;bg_loaded=true;local p="/WIDGETS/BF_Dashboard/background.png";if fstat(p)then bg=Bitmap.open(p)end end
local function cells_from_pack(v)v=num(v,0);if v<=0 then return 0 end;local c=math.floor((v/4.35)+1.0);if c<1 then c=1 elseif c>12 then c=12 end;return c end
local function pct_from_cell(v)v=num(v,0);if v>=4.20 then return 100 end;if v>=3.80 then return math.floor(50+((v-3.80)/0.40)*50+0.5)end;if v>=3.50 then return math.floor(15+((v-3.50)/0.30)*35+0.5)end;if v>=3.30 then return math.floor(((v-3.30)/0.20)*15+0.5)end;return 0 end
local function txpct(v)v=num(v,0);if v<=0 then return 0 end;local p=(v-6.6)/(8.4-6.6)*100;if p<0 then p=0 elseif p>100 then p=100 end;return p end
local function rate(v)local r=math.floor(num(v,-1)+0.5);local m={[0]="4Hz",[1]="50Hz",[2]="150",[3]="250",[4]="500",[5]="F500",[6]="F1000",[7]="D50",[8]="D250",[9]="D500",[10]="F500",[11]="F1000"};return m[r]or tostring(r)end
local function gps_present(gps,sats,gspd,galt,alt,hdg)if gps~=nil and gps~=0 and tostring(gps)~="0"and tostring(gps)~="--"then return true end;return num(sats,0)>0 or num(gspd,0)>0 or num(galt,0)~=0 or num(alt,0)~=0 or num(hdg,0)~=0 end
local function ring(x,y,p,mah,col)p=math.max(0,math.min(100,math.floor(num(p,0)+0.5)));mah=math.max(0,math.floor(num(mah,0)+0.5));local c=GREEN;if p<20 then c=RED elseif p<40 then c=ORANGE end;lcd.drawAnnulus(x,y,S(30),S(43),0,360,DARKGREY);if p>0 then lcd.drawAnnulus(x,y,S(30),S(43),270,270+p*3.6,c)end;lcd.drawText(x,y-S(5),p.."%",CENTER+VCENTER+MIDSIZE+BOLD+col);lcd.drawText(x,y+S(15),mah.."mAh",CENTER+VCENTER+SMLSIZE+col)end
local function bars(x,y,lq)lq=math.max(0,math.min(100,math.floor(num(lq,0)+0.5)));local a=math.floor((lq+19)/20);for i=1,5 do local c=DARKGREY;if i<=a then if i<=1 then c=RED elseif i==2 then c=ORANGE elseif i==3 then c=YELLOW else c=GREEN end end;lcd.drawFilledRectangle(x+(i-1)*S(7),y+S(10-i*2),S(5),S(4+i*2),c)end end
local function smallbat(x,y,w,h,p,c)p=math.max(0,math.min(100,math.floor(num(p,0)+0.5)));local f=math.floor((w-4)*p/100+0.5);lcd.drawRectangle(X(x),Y(y),S(w),S(h),WHITE);lcd.drawFilledRectangle(X(x+w),Y(y+4),S(3),S(h-8),WHITE);if f>0 then lcd.drawFilledRectangle(X(x+2),Y(y+2),S(f),S(h-4),c)end end
local function icon(n,x,y)local b=icons[n];if b then lcd.drawBitmap(b,X(x),Y(y))end end
local function top(x,t,v,c)lcd.drawText(X(x),Y(8),t,CENTER+VCENTER+WHITE);lcd.drawText(X(x),Y(28),v,CENTER+VCENTER+MIDSIZE+c)end
local function update_pic(show)local n=model.getInfo().name or"";if n==""or show~=1 then return default_pic end;local s=string.gsub(n,"%s+","_");local p="/WIDGETS/BF_Dashboard/"..s..".png";if fstat(p)then if not model_pic then model_pic=Bitmap.open(p)end;return model_pic end;return default_pic end
local function create(zone,opts)cache={};default_pic=Bitmap.open("/WIDGETS/BF_Dashboard/default.png");for _,n in ipairs({"sat","alt","hdg","home","batt","bolt","stop","clock","ant","link"})do icons[n]=Bitmap.open("/WIDGETS/BF_Dashboard/ico_"..n..".png")end;return{zone=zone,options=opts}end
local function update(w,opts)w.options=opts;cache={};bg_loaded=false end
local function background(w)end
local function refresh(w,event,touch)
 local sw=LCD_W or w.zone.w;local sh=LCD_H or w.zone.h;UI_SCALE=math.min(sw/BASE_W,sh/BASE_H)
 lcd.setColor(CUSTOM_COLOR,w.options.BackgroundColor);local bgc=lcd.getColor(CUSTOM_COLOR);lcd.setColor(CUSTOM_COLOR,w.options.SquareColor);local line=lcd.getColor(CUSTOM_COLOR);lcd.setColor(CUSTOM_COLOR,w.options.ValueColor);local vc=lcd.getColor(CUSTOM_COLOR)
 lcd.drawFilledRectangle(0,0,sw,sh,bgc);if w.options.UsePngBg==1 then loadbg();if bg then lcd.drawBitmap(bg,0,0)end end
 local fm=str(sensor({"FM","FMode","FlightMode","Flight Mode"},"--"),"--");local dis=(string.find(fm,"!",1,true)~=nil)or(string.find(fm,"*",1,true)~=nil);local armed=(fm~="--")and not dis;local clean=string.gsub(string.gsub(fm,"!",""),"%*","");if clean==""then clean="--"end
 if armed and not was_armed then armed_seconds=0;max_current=0;max_power=0;max_speed=0 end;was_armed=armed;local now=getRtcTime();if now~=last_rtc then last_rtc=now;if armed then armed_seconds=armed_seconds+1 end end
 local txv=num(getValue("tx-voltage")or getValue("TxBt"),0);local lq=num(sensor({"RQly","RQLY","RQLy","LQ"},0),0);local snr=num(sensor({"RSNR","RSnr","SNR"},0),0);local rfmd=sensor({"RFMD","RFmd","Rate"},-1);local tpwr=num(sensor({"TPWR","TPwr","Pwr"},0),0)
 local rssi1=num(sensor({"1RSS","1RSSI","RSSI"},0),0);local rssi2=num(sensor({"2RSS","2RSSI"},0),0);local trss=num(sensor({"TRSS","TRssi","TRSSI"},0),0);local tqly=num(sensor({"TQly","TQLY","TQLy"},0),0)
 local pack=num(sensor({"RxBt","VFAS","Batt","Battery"},0),0);local curr=num(sensor({"Curr","Current"},0),0);local capa=num(sensor({"Capa","Fuel","mAh"},0),0);local bfpct=num(sensor({"Bat%","Batt%","Fuel%"},0),0)
 local gps=sensor({"GPS","Gps"},nil);local gspd=num(sensor({"GSpd","GSPD","Gspd","GPS Speed","GSpeed"},0),0);local hdg=num(sensor({"Hdg","HDG","Heading"},0),0);local galt=num(sensor({"GAlt","GALT","GPS Alt","GPSAlt"},0),0);local balt=num(sensor({"Alt","ALT","Altitude"},0),0);local sats=num(sensor({"Sats","SATS","Sat","GPS Sats"},0),0);local dist=num(sensor({"Dist","HomeDist","Home","Distance"},0),0);local alt=(galt~=0)and galt or balt
 local cells=cells_from_pack(pack);local cell=(cells>0 and pack>0)and(pack/cells)or 0;local bp=(cell>0)and pct_from_cell(cell)or bfpct;local power=pack*curr;if armed then if curr>max_current then max_current=curr end;if power>max_power then max_power=power end;if gspd>max_speed then max_speed=gspd end end
 local txp=txpct(txv);local txc=GREEN;if txp<25 then txc=RED elseif txp<45 then txc=ORANGE end
 local xs={62,132,202,278,352,432};top(xs[1],"FM",clean,vc);lcd.drawText(X(xs[1]),Y(47),dis and"DISARMED"or"ARMED",CENTER+VCENTER+SMLSIZE+(dis and RED or GREEN));vl(96,8,42,line);top(xs[2],"LQ",math.floor(lq+0.5).."%",vc);bars(X(xs[2]-20),Y(47),lq);vl(166,8,42,line);top(xs[3],"SNR",math.floor(snr+0.5).."dB",vc);vl(238,8,42,line);top(xs[4],"RATE",rate(rfmd),vc);vl(315,8,42,line);local ptxt=tpwr>=1000 and string.format("%.1fW",tpwr/1000)or string.format("%dmW",math.floor(tpwr+0.5));top(xs[5],"PWR",ptxt,vc);vl(391,8,42,line);lcd.drawText(X(xs[6]),Y(8),"Tx",CENTER+VCENTER+WHITE);lcd.drawText(X(xs[6]),Y(28),string.format("%.1fV",txv),CENTER+VCENTER+MIDSIZE+txc);smallbat(424,44,36,12,txp,txc)
 ring(X(68),Y(102),bp,capa,vc);lcd.drawText(X(18),Y(154),"BATTERY REMAINING",SMLSIZE+WHITE);box(12,171,150,54,RED);lcd.drawText(X(43),Y(181),"PACK",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(124),Y(181),"CELL",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(43),Y(196),string.format("%.1fV",pack),CENTER+VCENTER+SMLSIZE+vc);lcd.drawText(X(124),Y(196),string.format("%.2fV",cell),CENTER+VCENTER+SMLSIZE+vc);hl(22,203,128,WHITE);lcd.drawText(X(43),Y(213),"CURR",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(124),Y(213),"POWER",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(43),Y(229),string.format("%.1fA",curr),CENTER+VCENTER+SMLSIZE+vc);lcd.drawText(X(124),Y(229),string.format("%.0fW",power),CENTER+VCENTER+SMLSIZE+vc)
 lcd.drawText(X(245),Y(64),"GPS SPEED",CENTER+VCENTER+WHITE);lcd.drawText(X(245),Y(101),string.format("%.0f",gspd),CENTER+VCENTER+XXLSIZE+BOLD+vc);lcd.drawText(X(245),Y(132),"km/h",CENTER+VCENTER+MIDSIZE+WHITE);if w.options.ShowImage==1 then local pic=update_pic(w.options.ShowImage);if pic then lcd.drawBitmap(pic,X(186),Y(121))end end
 box(337,57,133,67,CYAN);hl(348,91,111,WHITE);lcd.drawText(X(370),Y(70),"1RSS",CENTER+VCENTER+SMLSIZE+WHITE);local lab=(rssi2~=0)and"2RSS"or"TRSS";local val=(rssi2~=0)and rssi2 or trss;lcd.drawText(X(438),Y(70),lab,CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(370),Y(84),string.format("%ddB",rssi1),CENTER+VCENTER+SMLSIZE+vc);lcd.drawText(X(438),Y(84),string.format("%ddB",val),CENTER+VCENTER+SMLSIZE+vc);lcd.drawText(X(370),Y(104),"RQly",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(438),Y(104),"TQly",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(370),Y(118),math.floor(lq+0.5).."%",CENTER+VCENTER+SMLSIZE+vc);lcd.drawText(X(438),Y(118),math.floor(tqly+0.5).."%",CENTER+VCENTER+SMLSIZE+vc)
 box(337,130,133,77,CYAN);hl(349,149,108,WHITE);hl(349,168,108,WHITE);hl(349,187,108,WHITE);local gp=gps_present(gps,sats,gspd,galt,balt,hdg);local gl=sats>=4;icon("sat",345,135);if not gp then lcd.drawText(X(390),Y(141),"NO GPS",CENTER+VCENTER+SMLSIZE+WHITE)elseif not gl then lcd.drawText(X(390),Y(141),"NO FIX",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(445),Y(141),math.floor(sats+0.5),CENTER+VCENTER+MIDSIZE+vc)else lcd.drawText(X(386),Y(141),"SATS",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(445),Y(141),math.floor(sats+0.5),CENTER+VCENTER+MIDSIZE+vc)end;icon("alt",345,154);lcd.drawText(X(382),Y(160),"ALT",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(445),Y(160),gp and string.format("%.0fm",alt)or"--",CENTER+VCENTER+MIDSIZE+vc);icon("hdg",345,173);lcd.drawText(X(382),Y(179),"HDG",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(445),Y(179),gp and string.format("%.0fdeg",hdg)or"--",CENTER+VCENTER+MIDSIZE+vc);icon("home",345,192);lcd.drawText(X(391),Y(198),"DIST HOME",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(450),Y(198),gp and string.format("%.0fm",dist)or"--",CENTER+VCENTER+SMLSIZE+vc)
 box(8,232,464,36,line);vl(90,233,34,line);vl(190,233,34,line);vl(290,233,34,line);vl(386,233,34,line);icon("batt",20,239);smallbat(14,260,28,6,bp,(bp<20 and RED or GREEN));lcd.drawText(X(62),Y(241),"USED",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(62),Y(256),math.floor(capa+0.5).."mAh",CENTER+VCENTER+SMLSIZE+vc);icon("bolt",105,241);lcd.drawText(X(145),Y(241),"MAX SPEED",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(145),Y(256),string.format("%.0fkm/h",max_speed),CENTER+VCENTER+SMLSIZE+vc);icon("home",209,241);lcd.drawText(X(250),Y(241),"DIST HOME",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(250),Y(256),string.format("%.0fm",dist),CENTER+VCENTER+SMLSIZE+vc);icon("stop",310,241);local mm=math.floor(armed_seconds/60);local ss=armed_seconds%60;lcd.drawText(X(352),Y(241),"FLIGHT",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(352),Y(256),string.format("%02d:%02d",mm,ss),CENTER+VCENTER+SMLSIZE+vc);icon("clock",402,241);local tm=getDateTime();lcd.drawText(X(448),Y(241),"TIME",CENTER+VCENTER+SMLSIZE+WHITE);lcd.drawText(X(448),Y(256),string.format("%02d:%02d:%02d",tm.hour,tm.min,tm.sec),CENTER+VCENTER+SMLSIZE+vc)
end
return{name=NAME,options=options,create=create,update=update,background=background,refresh=refresh}
